[package]
name = "serde_json_compare"
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
serde = { version = "1.0.153", features = ["derive"] }
serde_json = "1.0.94"

[dev-dependencies]
insta = "1.28.0"
